using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace StudentJobHelperSystem.Data.Migrations
{
    public partial class AutoGeneratedIdsAndSeedDb : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 5);

            migrationBuilder.DeleteData(
                table: "JobAds",
                keyColumn: "Id",
                keyValue: new Guid("d8b20ada-d5c2-4219-94d9-9675f87ec53e"));

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1001, "Engineers and Technicians" },
                    { 1002, "Healthcare and Pharmacy" },
                    { 1003, "Real-estate" },
                    { 1004, "Legal" },
                    { 1005, "Media, Publishing" }
                });

            migrationBuilder.InsertData(
                table: "JobAds",
                columns: new[] { "Id", "CategoryId", "CityOfWork", "Description", "Email", "EmployerId", "ForeignLanguage", "HomeOffice", "LogoUrl", "OffDaysCount", "PhoneNumber", "Salary", "Title", "TypeOfEmployment", "WorkerId" },
                values: new object[] { new Guid("d981d528-0a80-4404-b5b4-b33b849550fa"), 1001, "Sofia", "fasdgsgdfgdfg", "employer@gmail.com", new Guid("53f74e02-0c81-45b2-b443-912f2a37d410"), "English", false, "sdgsdfgdfgdgh", 15, "0876545222", 2500.00m, "nz", "Permanent", new Guid("1461a7de-14e2-4031-a2d9-5edc19df3b8e") });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1002);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1003);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1004);

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1005);

            migrationBuilder.DeleteData(
                table: "JobAds",
                keyColumn: "Id",
                keyValue: new Guid("d981d528-0a80-4404-b5b4-b33b849550fa"));

            migrationBuilder.DeleteData(
                table: "Categories",
                keyColumn: "Id",
                keyValue: 1001);

            migrationBuilder.InsertData(
                table: "Categories",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Engineers and Technicians" },
                    { 2, "Healthcare and Pharmacy" },
                    { 3, "Real-estate" },
                    { 4, "Legal" },
                    { 5, "Media, Publishing" }
                });

            migrationBuilder.InsertData(
                table: "JobAds",
                columns: new[] { "Id", "CategoryId", "CityOfWork", "Description", "Email", "EmployerId", "ForeignLanguage", "HomeOffice", "LogoUrl", "OffDaysCount", "PhoneNumber", "Salary", "Title", "TypeOfEmployment", "WorkerId" },
                values: new object[] { new Guid("d8b20ada-d5c2-4219-94d9-9675f87ec53e"), 1, "Sofia", "fasdgsgdfgdfg", "employer@gmail.com", new Guid("53f74e02-0c81-45b2-b443-912f2a37d410"), "English", false, "sdgsdfgdfgdgh", 15, "0876545222", 2500.00m, "nz", "Permanent", new Guid("1461a7de-14e2-4031-a2d9-5edc19df3b8e") });
        }
    }
}
